openapi: 3.0.0
info:
  title: API de Escola
  description: API para gerenciamento de alunos
  version: 1.0.0

paths:
  /conectar:
    get:
      summary: Conecta ao banco de dados
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  connection:
                    type: object
                    properties:
                      host:
                        type: string
                      port:
                        type: integer
                      database:
                        type: string
                      user:
                        type: string
                      password:
                        type: string
  /criar_aluno:
    post:
      summary: Cria um novo aluno
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Aluno'
      responses:
        201:
          description: Criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aluno'
  /alunos:
    get:
      summary: Lista todos os alunos
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Aluno'
  /alunos/nome/<nome>:
    get:
      summary: Lista os alunos pelo nome
      parameters:
        - name: nome
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Aluno'
  /alunos/nota/<nota>:
    get:
      summary: Lista os alunos pela nota
      parameters:
        - name: nota
          in: path
          required: true
          schema:
            type: number
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Aluno'
  /atualizar_aluno/<id>:
    post:
      summary: Atualiza um aluno
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Aluno'
      responses:
        200:
          description: Atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aluno'
  /deletar_aluno/<id>:
    delete:
      summary: Deleta um aluno
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Deletado com sucesso
          content:
            application/json:
              schema:
                type: integer

components:
  schemas:
    Aluno:
      type: object
      properties:
        nome:
          type: string
        idade:
          type: integer
        nota_primeiro_semestre:
          type: number
        nota_segundo_semestre:
          type: number
        nome_
